spring.application.name=trade-mcp-server

server.port=8081
server.address=127.0.0.1
spring.ai.mcp.server.name=trade-mcp-server
spring.ai.mcp.server.veersion=1.1.5
spring.ai.mcp.server.type=ASYNC

spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
spring.ai.mcp.server.capabilities.resource=true

logging.level.org.springframework.ai=DEBUG
logging.level.io.modelcontextprotocol=INFO


# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# SQL Init
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false