CREATE TABLE ledger_balances (
    ledger_balance_id UUID NOT NULL PRIMARY KEY,
    balance_type VARCHAR(100) NOT NULL,
    net_balance NUMERIC(15, 6) NOT NULL,
    posting_date DATE NOT NULL,
    file_name VARCHAR(500) NOT NULL,
    create_date_time TIMESTAMP NOT NULL
);

CREATE TABLE ledger_records (
    ledger_record_id UUID NOT NULL PRIMARY KEY,
    particulars VARCHAR(1000) NOT NULL,
    posting_date DATE NOT NULL,
    cost_center VARCHAR(50) NOT NULL,
    voucher_type VARCHAR(50),
    debit NUMERIC(15, 6) NOT NULL,
    credit NUMERIC(15, 6) NOT NULL,
    net_balance NUMERIC(15, 6),
    file_name VARCHAR(500) NOT NULL,
    create_date_time TIMESTAMP NOT NULL
);

CREATE TABLE trade_records (
    id UUID NOT NULL PRIMARY KEY,
    symbol VARCHAR(50) NOT NULL,
    isin VARCHAR(50),
    trade_date DATE NOT NULL,
    exchange VARCHAR(50) NOT NULL,
    segment VARCHAR(50),
    series VARCHAR(50),
    trade_type VARCHAR(10),
    auction BOOLEAN DEFAULT FALSE,
    quantity NUMERIC(15, 6) NOT NULL,
    price NUMERIC(15, 6) NOT NULL,
    trade_id BIGINT,
    order_id VARCHAR(100),
    order_execution_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT trade_records_trade_type_check CHECK (trade_type IN ('buy', 'sell'))
);

CREATE TABLE mutual_fund_broker_account (
    broker_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    broker_name VARCHAR(255) NOT NULL,
    account_id VARCHAR(100) NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE mutual_fund (
    mutual_fund_id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    broker_account_id BIGINT NOT NULL,
    mutual_fund_name VARCHAR(255) NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mutual_fund_broker_account FOREIGN KEY (broker_account_id)
        REFERENCES mutual_fund_broker_account (broker_account_id)
);

CREATE TABLE mutual_fund_txn (
    mutual_fund_txn_id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    mutual_fund_id BIGINT NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    txn_date TIMESTAMP NOT NULL,
    units NUMERIC(18, 3) DEFAULT 0 NOT NULL,
    avg_price NUMERIC(18, 3) DEFAULT 0 NOT NULL,
    txn_type VARCHAR DEFAULT 'BUY' NOT NULL,
    CONSTRAINT fk_mutual_fund_txn_mutual_fund FOREIGN KEY (mutual_fund_id)
        REFERENCES mutual_fund (mutual_fund_id)
);

CREATE TABLE mutual_fund_value (
    val_id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    mutual_fund_id BIGINT NOT NULL,
    total_value NUMERIC(18, 2) NOT NULL,
    value_as_of_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_mutual_fund_value_mutual_fund FOREIGN KEY (mutual_fund_id)
        REFERENCES mutual_fund (mutual_fund_id)
);
