<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.6</version>
		<relativePath />
	</parent>
	<groupId>com.trading</groupId>
	<artifactId>trade-parent-reactor</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>trade-parent-reactor</name>
	<modules>
		<module>trade-model</module>
		<module>trade-repository</module>
		<module>trade-batch</module>
		<module>trade-mcp-server</module>
		<module>trade-rest</module>
	</modules>


	<properties>
		<java.version>25</java.version>
		<maven.compiler.source>25</maven.compiler.source>
		<maven.compiler.target>25</maven.compiler.target>
		<spring-ai.version>1.1.5</spring-ai.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-webflux</artifactId>
				<version>4.0.6</version>
			</dependency>

			<!-- MCP Server Starter -->
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-starter-mcp-server-webflux</artifactId>
				<version>1.1.5</version>
			</dependency>
			<!-- Optional: Ollama integration -->

			<!-- Source:
		https://mvnrepository.com/artifact/org.springframework.ai/spring-ai-ollama -->
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-ollama</artifactId>
				<version>1.1.5</version>
			</dependency>

			<!-- Logging (included by default, but explicit if needed) -->

			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-logging</artifactId>
			</dependency>


			<!-- Database -->
			<dependency>
				<groupId>org.postgresql</groupId>
				<artifactId>postgresql</artifactId>
				<version>42.7.11</version>
			</dependency>

			<!-- H2 for testing -->
			<dependency>
				<groupId>com.h2database</groupId>
				<artifactId>h2</artifactId>
				<version>2.4.240</version>
				<scope>test</scope>
			</dependency>
		</dependencies>

	</dependencyManagement>


	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

</project>