spring.application.name=coin-order-history-import
spring.main.web-application-type=none
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.enabled=false
spring.sql.init.mode=never
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
spring.jpa.hibernate.ddl-auto=none
batch.coin.chunk-size=100
logging.level.org.springframework.jdbc=INFO
logging.level.org.hibernate=OFF
